// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbfaxRYcqa5pzhXeQA5vZRyEPLX2Rc2y4',
    appId: '1:797791224045:web:312acfc945bb62e61a0ce4',
    messagingSenderId: '797791224045',
    projectId: 'bme-hospital-manager',
    authDomain: 'bme-hospital-manager.firebaseapp.com',
    databaseURL: 'https://bme-hospital-manager-default-rtdb.firebaseio.com',
    storageBucket: 'bme-hospital-manager.firebasestorage.app',
    measurementId: 'G-6K8W2ZXBZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmMDpLduheSFuUKSjTtUyU5a5XgmWYZa4',
    appId: '1:797791224045:android:b462e22f2f4396121a0ce4',
    messagingSenderId: '797791224045',
    projectId: 'bme-hospital-manager',
    databaseURL: 'https://bme-hospital-manager-default-rtdb.firebaseio.com',
    storageBucket: 'bme-hospital-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbhS4V2-6t_Y5pD0QBxYpAP3SCzYWnflc',
    appId: '1:797791224045:ios:96418df3b316886b1a0ce4',
    messagingSenderId: '797791224045',
    projectId: 'bme-hospital-manager',
    databaseURL: 'https://bme-hospital-manager-default-rtdb.firebaseio.com',
    storageBucket: 'bme-hospital-manager.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbhS4V2-6t_Y5pD0QBxYpAP3SCzYWnflc',
    appId: '1:797791224045:ios:96418df3b316886b1a0ce4',
    messagingSenderId: '797791224045',
    projectId: 'bme-hospital-manager',
    databaseURL: 'https://bme-hospital-manager-default-rtdb.firebaseio.com',
    storageBucket: 'bme-hospital-manager.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbfaxRYcqa5pzhXeQA5vZRyEPLX2Rc2y4',
    appId: '1:797791224045:web:e2ddbe34b1c74f2b1a0ce4',
    messagingSenderId: '797791224045',
    projectId: 'bme-hospital-manager',
    authDomain: 'bme-hospital-manager.firebaseapp.com',
    databaseURL: 'https://bme-hospital-manager-default-rtdb.firebaseio.com',
    storageBucket: 'bme-hospital-manager.firebasestorage.app',
    measurementId: 'G-89H0QVPW87',
  );
}
